// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7I9pN6awauErBET6dhCTj5jJBUElV-ZQ',
    appId: '1:598861259077:web:d81d97c6f4b163e3c75e2c',
    messagingSenderId: '598861259077',
    projectId: 'practical-exam-e4f6c',
    authDomain: 'practical-exam-e4f6c.firebaseapp.com',
    storageBucket: 'practical-exam-e4f6c.appspot.com',
    measurementId: 'G-FB0L4R97V9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-2bHfGzAKQyRtxrBsqxC-Y6fjt9D_V4w',
    appId: '1:598861259077:android:8807ab4c956b87d2c75e2c',
    messagingSenderId: '598861259077',
    projectId: 'practical-exam-e4f6c',
    storageBucket: 'practical-exam-e4f6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAntMUSLAMhu4XxdNV7Jc2RO-eF_25U_Vg',
    appId: '1:598861259077:ios:4ccd655efb4e4f6cc75e2c',
    messagingSenderId: '598861259077',
    projectId: 'practical-exam-e4f6c',
    storageBucket: 'practical-exam-e4f6c.appspot.com',
    iosBundleId: 'com.example.precticalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAntMUSLAMhu4XxdNV7Jc2RO-eF_25U_Vg',
    appId: '1:598861259077:ios:b6e6fb2d3f7b78fcc75e2c',
    messagingSenderId: '598861259077',
    projectId: 'practical-exam-e4f6c',
    storageBucket: 'practical-exam-e4f6c.appspot.com',
    iosBundleId: 'com.example.precticalExam.RunnerTests',
  );
}
